const { getJID } = require('../utils/helpers');
const { safeSend } = require('../utils/send');

const OPENROUTER_KEY = process.env.OPENROUTER_API_KEY;
const MODELS = [
  'google/gemma-4-31b-it:free',
  'meta-llama/llama-3.2-3b-instruct:free',
  'deepseek/deepseek-v4-flash:free',
];

async function askAI(prompt, system = 'You are a helpful assistant. Be concise.') {
  for (const model of MODELS) {
    try {
      const res = await fetch('https://openrouter.ai/api/v1/chat/completions', {
        method: 'POST',
        headers: {
          'Authorization': 'Bearer ' + OPENROUTER_KEY,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          model,
          messages: [
            { role: 'system', content: system },
            { role: 'user', content: prompt }
          ],
          max_tokens: 500,
        }),
      });
      const data = await res.json();
      const reply = data.choices?.[0]?.message?.content;
      if (reply) return reply;
    } catch (_) {}
  }
  return null;
}

async function handleAI(sock, msg, cmd, args) {
  const jid = getJID(msg);

  if (!OPENROUTER_KEY) {
    await safeSend(sock, jid, { text: '❌ Set OPENROUTER_API_KEY in .env to use AI commands.' });
    return;
  }

  const input = args.join(' ');

  if (!input && !['advice'].includes(cmd)) {
    await safeSend(sock, jid, { text: `❌ Usage: !${cmd} <your input>` });
    return;
  }

  await safeSend(sock, jid, { text: '🤖 Thinking...' });

  try {
    let reply;

    switch (cmd) {
      case 'ask':
      case 'ai':
        reply = await askAI(input);
        break;

      case 'summarize':
        reply = await askAI(input, 'Summarize the following text in 3-5 bullet points. Be concise.');
        break;

      case 'translate':
        const [lang, ...rest] = args;
        if (!lang || !rest.length) { await safeSend(sock, jid, { text: '❌ Usage: !translate <language> <text>' }); return; }
        reply = await askAI(rest.join(' '), `Translate the following text to ${lang}. Only return the translation, nothing else.`);
        break;

      case 'code':
        reply = await askAI(input, 'You are a coding assistant. Provide clean working code with a brief explanation. Keep it concise.');
        break;

      case 'sentiment':
        reply = await askAI(input, 'Analyze the sentiment of this text. Say Positive, Negative, or Neutral and explain in 1-2 sentences why.');
        break;

      case 'imagine':
        reply = await askAI(input, 'Describe in vivid detail what this image would look like if generated by AI. Be creative and descriptive in 3-4 sentences.');
        break;

      case 'advice':
        const topic = input || 'life in general';
        reply = await askAI(topic, 'You are a wise life coach. Give practical, honest, and motivating advice. Keep it under 5 sentences.');
        break;

      case 'story':
        reply = await askAI(input, 'Write a short creative story in 5-8 sentences. Make it engaging with a beginning, middle and end.');
        break;

      case 'poem':
        reply = await askAI(input, 'Write a short beautiful poem about this topic. Make it rhyme and feel emotional. 4-8 lines.');
        break;

      case 'recipe':
        reply = await askAI(input, 'Give a simple recipe for this dish. List ingredients first then steps. Keep it practical and easy to follow.');
        break;

      case 'debate':
        reply = await askAI(input, 'Present both sides of this debate topic fairly. Give 2-3 points for each side. Be balanced and objective.');
        break;

      case 'roastai':
        reply = await askAI(input, 'Write a funny playful roast about this person or topic. Keep it lighthearted and humorous, not mean. Max 3 sentences.');
        break;

      case 'pickup':
        reply = await askAI(input || 'general', 'Generate a creative and funny pickup line related to this topic. Make it clever and charming.');
        break;

      default:
        reply = await askAI(input);
    }

    if (reply) {
      await safeSend(sock, jid, { text: reply });
    } else {
      await safeSend(sock, jid, { text: '❌ AI did not respond. Try again.' });
    }
  } catch (err) {
    await safeSend(sock, jid, { text: '❌ AI error: ' + err.message });
  }
}

module.exports = { handleAI };
