const { getJID, getMessageText } = require('../utils/helpers');
const logger = require('../utils/logger');

const ANTHROPIC_KEY = process.env.ANTHROPIC_API_KEY;

async function callClaude(system, userMsg) {
  const res = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-api-key': ANTHROPIC_KEY,
      'anthropic-version': '2023-06-01',
    },
    body: JSON.stringify({
      model: 'claude-haiku-4-5-20251001',
      max_tokens: 1024,
      system,
      messages: [{ role: 'user', content: userMsg }],
    }),
  });
  const data = await res.json();
  if (data.error) throw new Error(data.error.message);
  return data.content?.[0]?.text || 'No response.';
}

async function handleAI(sock, msg, cmd, args) {
  const jid = getJID(msg);
  const input = args.join(' ');

  if (!ANTHROPIC_KEY) {
    await sock.sendMessage(jid, { text: '❌ Set ANTHROPIC_API_KEY in .env to use AI commands.' });
    return;
  }

  if (!input) {
    await sock.sendMessage(jid, { text: `❌ Usage: !${cmd} <text>` });
    return;
  }

  await sock.sendMessage(jid, { text: '🤔 Processing...' });

  try {
    let reply;
    switch (cmd) {
      case 'ask':
      case 'ai':
      case 'chat':
        reply = await callClaude(
          'You are a helpful WhatsApp assistant. Be concise and friendly. Plain text only, no markdown.',
          input
        );
        break;
      case 'summarize':
        reply = await callClaude(
          'Summarize the following text in concise bullet points. Plain text only.',
          input
        );
        break;
      case 'translate': {
        const [lang, ...rest] = args;
        const text = rest.join(' ');
        if (!text) { await sock.sendMessage(jid, { text: '❌ Usage: !translate <language> <text>' }); return; }
        reply = await callClaude(
          `Translate the following text to ${lang}. Return only the translation, nothing else.`,
          text
        );
        break;
      }
      case 'code':
        reply = await callClaude(
          'You are a coding assistant. Answer coding questions with clear explanations and code examples. Keep it concise.',
          input
        );
        break;
      case 'sentiment':
        reply = await callClaude(
          'Analyze the sentiment of the following text. Say whether it is Positive, Negative, or Neutral, then give a 1-sentence explanation.',
          input
        );
        break;
      case 'imagine':
        reply = await callClaude(
          'Describe in vivid detail what this image prompt would look like if generated by an AI image model. Be creative and descriptive.',
          input
        );
        break;
      default:
        reply = await callClaude('You are a helpful assistant.', input);
    }
    await sock.sendMessage(jid, { text: `🤖 ${reply}` });
  } catch (err) {
    logger.error('AI error:', err);
    await sock.sendMessage(jid, { text: '❌ AI request failed. Try again.' });
  }
}

module.exports = { handleAI };
